var app = new Vue({
	el:'#app',
	data:{
		count:[
			{digtial:1},
			{digtial:2},
			{digtial:3},
			{digtial:1},
			{digtial:2},
			{digtial:3},
			{digtial:1},
			{digtial:2},
			{digtial:3},
			{digtial:4}
		],
		color:[
			{"background-color":"red"},
			{"background-color":"green"},
			{"background-color":"black"},
			{"background-color":"gray"},
			{"background-color":"red"},
			{"background-color":"green"},
			{"background-color":"black"},
			{"background-color":"gray"},
			{"background-color":"red"},
			{"background-color":"green"}
		]
	}
})